In [5]:
pip install -U scikit-fuzzy

   ---------------------------------------- 0.0/920.8 kB ? eta -:--:--
   ---------------------------------------- 920.8/920.8 kB 8.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [7]:
from sklearn import datasets
import numpy as np
from sklearn.metrics import confusion_matrix
import skfuzzy

In [11]:
iris = datasets.load_iris()

In [13]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [25]:
# Aplicação do algoritmo definindo três cluster (c = 3) e passando a matriz transposta (iris.data.T). Os outros parâmetros são obrigatórios e são os default indicados na documentação\n",

r = skfuzzy.cmeans(data = iris.data.T, c = 3, m = 2, error = 0.005,
                  maxiter = 1000, init = None)
r

(array([[5.88824938, 2.76082318, 4.36295339, 1.39680049],
        [6.77418398, 3.05214131, 5.64575067, 2.05314841],
        [5.00396436, 3.4141226 , 1.48276057, 0.25352166]]),
 array([[2.30446295e-03, 1.66629884e-02, 1.37683053e-02, 2.24829309e-02,
         3.76219812e-03, 4.48343877e-02, 1.40129272e-02, 3.11775888e-04,
         4.77519807e-02, 1.19456306e-02, 2.17691573e-02, 5.43676504e-03,
         2.01980019e-02, 5.18247358e-02, 7.26404019e-02, 1.04391682e-01,
         3.55963067e-02, 2.28897640e-03, 6.55961336e-02, 1.41647115e-02,
         2.18736372e-02, 1.03793440e-02, 2.75212353e-02, 1.44772554e-02,
         2.32652125e-02, 1.84763857e-02, 3.58607248e-03, 4.56767998e-03,
         4.33017146e-03, 1.42139523e-02, 1.48128751e-02, 1.77095802e-02,
         4.11648096e-02, 6.35095461e-02, 1.03502182e-02, 1.02065995e-02,
         2.42644795e-02, 6.18423855e-03, 4.11109565e-02, 1.17861390e-03,
         3.58437465e-03, 1.02338317e-01, 3.21968451e-02, 1.43954463e-02,
         3.81577380e-

In [29]:
# Obtendo as porcentagens de um registros pertencer a um cluster, que está na posição 1 da matriz retornada\n",

previsoes = r[1]
previsoes

array([[2.30446295e-03, 1.66629884e-02, 1.37683053e-02, 2.24829309e-02,
        3.76219812e-03, 4.48343877e-02, 1.40129272e-02, 3.11775888e-04,
        4.77519807e-02, 1.19456306e-02, 2.17691573e-02, 5.43676504e-03,
        2.01980019e-02, 5.18247358e-02, 7.26404019e-02, 1.04391682e-01,
        3.55963067e-02, 2.28897640e-03, 6.55961336e-02, 1.41647115e-02,
        2.18736372e-02, 1.03793440e-02, 2.75212353e-02, 1.44772554e-02,
        2.32652125e-02, 1.84763857e-02, 3.58607248e-03, 4.56767998e-03,
        4.33017146e-03, 1.42139523e-02, 1.48128751e-02, 1.77095802e-02,
        4.11648096e-02, 6.35095461e-02, 1.03502182e-02, 1.02065995e-02,
        2.42644795e-02, 6.18423855e-03, 4.11109565e-02, 1.17861390e-03,
        3.58437465e-03, 1.02338317e-01, 3.21968451e-02, 1.43954463e-02,
        3.81577380e-02, 1.92378733e-02, 1.58511437e-02, 1.76648505e-02,
        1.55285918e-02, 2.00927050e-03, 4.53542194e-01, 7.63242372e-01,
        3.67875006e-01, 8.70479771e-01, 7.57804978e-01, 9.737918

In [39]:
# Visualização da probabilidade de um registro pertencer a cada um dos cluster (o somatório é 1.0 que indica 100%)\n

for x in range(150):
    print(previsoes[0][x], previsoes[1][x], previsoes[2][x],)

0.002304462947565854 0.0010718928144125186 0.9966236442380216
0.01666298842217861 0.007502439618441968 0.9758345719593795
0.013768305319446988 0.006417483718009593 0.9798142109625434
0.02248293088863016 0.010113427812721055 0.9674036412986488
0.003762198122882805 0.0017678803033480493 0.9944699215737691
0.04483438771633167 0.020629950971216844 0.9345356613124516
0.014012927210506494 0.006507571999257557 0.9794795007902359
0.00031177588823607814 0.0001412884162904299 0.9995469356954734
0.04775198065405181 0.021913567264352653 0.9303344520815955
0.011945630569644745 0.005344968832048179 0.9827094005983071
0.021769157317166967 0.010205304743172916 0.9680255379396602
0.005436765037850068 0.002432799146146146 0.9921304358160038
0.02019800194543712 0.009182229583342196 0.9706197684712207
0.05182473575222348 0.02524654590584492 0.9229287183419317
0.07264040185055445 0.03764499766049835 0.8897146004889471
0.10439168239326219 0.054325930335814905 0.841282387270923
0.03559630667308338 0.01750216

In [41]:
# Geração de matriz de contingência para comparação com as classes originais da base de dados\n",

previsoes_ = previsoes.argmax(axis = 0)
resultado = confusion_matrix(iris.target, previsoes_)
resultado

array([[ 0,  0, 50],
       [47,  3,  0],
       [13, 37,  0]], dtype=int64)